from file import *
from basic_func import *
f = SimpleFile(r"D:\self\SimpleFile\SimpleFile\sample.txt", open_mode = OpenMode.READ)
def foo(x):
    if x =="a":
        return "1"
    else:
        return "2"
print(f.contains("issdf"))
# print(f.delete_char_at(LocationIndex(3)))
# print(f.read_next_paragraph())
# print(f.read_next_sentence())

# print(f.append("Naeem"))
# print(f.replace_by_loc(LocationIndex(1), LocationIndex(3),"IOUuuuu"))
# print(f.replace_char_at(LocationIndex(0), "z"))
# print(f.replace("Ahmed","Yousef"))
# print(f.read(LocationIndex(5), LocationIndex(10)))
# print(f.replace_char("a","z",cap = False))
# at = LocationIndex(index=10)
# print(f.read_char_at(at))
# print(f.read_word_at(LocationIndex(9)))
# print(f.read_next_char())
# print(f.read_sentence_at(LocationIndex(5)))
# print(f.read_paragraph_at(LocationIndex(5)))
# f.save_as(r"D:\self\SimpleFile\SimpleFile\tst12.txt")
# print(f.read_first_char(tmp=False))
# print(f.read_first_char())
# print(f.read_first_char())
# print(f.read_first_n_chars(2))
# print(f.read_first_n_words(2))
# print(f.read_first_n_paragraph(2))
# print(f.read_first_word(skip_non_char=False))
# # print(f.read_first_word(tmp=False))
# # print(f.read_first_char())
# print(f.read_first_sentence(contain_ender=False))
# # print(f.read_first_sentence(contain_ender=True))
# print(f.read_first_paragraph(tmp=False,contain_ender=True))
# print(f.read_first_word())
# print(f)
# print(f)
# print(f)
# f.replace_char(c_old = "a",c_new = "z", tmp=False, cap = True)
# # f.replace_char(c_old = "z",c_new = "a", tmp=False, cap = True)
# print(f)
# f.replace_char(c_old = "z",c_new = "a", tmp=False, cap = True)
# # f.replace_char(c_old = "a",c_new = "z", tmp=False, cap = True, )
#
# print(f)
# print(f.read_next_char(raise_error=False,skip_non_char =True))
# print(f.read_next_char(raise_error=False,skip_non_char =True))
# print(f.read_next_char(raise_error=False,skip_non_char =True))
# print(f.read_first_char())
# print(f.read_first_char(tmp =True))


# print(f.read_next_word(raise_error=False))
# print(f.read_next_char())
# # print(f.read_next_char())
# print(f.read_next_word(raise_error=False))
# print(f.read_next_word(raise_error=False))



#
#
# print(f.read_next_word(raise_error=False))
# print(f.read_next_word(raise_error=False))
# print(f.read_next_word(raise_error=False))
# print(f.read_next_word(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
# print(f.read_next_char(raise_error=False))
