from file import *

f = SimpleFile(r"D:\self\SimpleFile\SimpleFile\sample-c.txt")
# print(f.read_first_char())
# print(f.read_first_char())
# print(f.read_first_char())
# print(f.read_first_word(tmp=False))
# print(f.read_first_char())
# print(f.read_first_sentence(contain_ender=False))
# print(f.read_first_sentence(contain_ender=True))
# print(f.read_first_paragraph(tmp=False,contain_ender=True))
# print(f.read_first_word())
# print(f)
# print(f)
print(f)
f.replace_char(c_old = "a",c_new = "z", tmp=False, cap = True)
# f.replace_char(c_old = "z",c_new = "a", tmp=False, cap = True)
print(f)
f.replace_char(c_old = "z",c_new = "a", tmp=False, cap = True)
# f.replace_char(c_old = "a",c_new = "z", tmp=False, cap = True, )

print(f)
